version: "3.9"

services:
  backend:
    container_name: "kupi-backend-container"
    build:
      context: backend
      dockerfile: Dockerfile
    image: "kupi-backend-image"
    ports:
      - "4000:3000"
    env_file: .env
    restart: always

  postgres:
    container_name: "kupi-db-container"
    image: postgres:alpine
    restart: always
    env_file: .env
  
  frontend:
    container_name: "kupi-frontend-container"
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: "kupi-frontend-image"
    ports:
      - '8081:3000'
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - '8084:8080'
